version: '3.8'

services:
  app:
    build:
      context: .
      target: development
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    volumes:
      - .:/app
      - pyfeat_models:/root/.feat
    ports:
      - "8501:8501"
      - "49152-49170:49152-49170/udp"
    command: streamlit run src/ui/app.py
    environment:
      - PYTHONPATH=.
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - pyfeat_models:/root/.feat
    command: pytest
    environment:
      - PYTHONPATH=.
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  lint:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: ruff check .

volumes:
  pyfeat_models:
