"""initial empty

Revision ID: 0723754feef0
Revises: 
Create Date: 2026-03-06 12:48:21.093013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0723754feef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vibe_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('happy', sa.Float(), nullable=False),
    sa.Column('sad', sa.Float(), nullable=False),
    sa.Column('angry', sa.Float(), nullable=False),
    sa.Column('surprised', sa.Float(), nullable=False),
    sa.Column('fearful', sa.Float(), nullable=False),
    sa.Column('disgusted', sa.Float(), nullable=False),
    sa.Column('neutral', sa.Float(), nullable=False),
    sa.Column('dominant_emotion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vibe_records_session_id', 'vibe_records', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vibe_records_session_id', table_name='vibe_records')
    op.drop_table('vibe_records')
    op.drop_table('sessions')
    # ### end Alembic commands ###
